version: '2.1'

volumes:
  mysql:
    driver: local
  backup:
    driver: local


services:
  webserver:
    build: .
    restart: always
    ports:
      - 800:8000
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_DATABASE: movie_kg
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: [
                '--character-set-server=utf8mb4',
                '--collation-server=utf8mb4_unicode_ci'
        ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: movie_kg
      MYSQL_MAX_ALLOWED_PACKET: 128M
      MYSQL_INNODB_LOG_FILE_SIZE: 64M
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup